version: '3.8'

services:
  postgres:
    container_name: nest-clean-pg
    build:
      context: ./
      dockerfile: postgres/Dockerfile
    image: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}
    volumes:
      - ./postgres/data/pg:/data/postgress
    restart: on-failure
    tty: true
    